# Generated by Django 4.0.5 on 2022-07-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='История')),
                ('img', models.ImageField(upload_to='History/%Y/%m/%d', verbose_name='Фото')),
                ('date', models.CharField(help_text='2000-2005', max_length=25, verbose_name='Дата')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Истоия',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
