# Generated by Django 4.0.5 on 2022-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_myhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhistory',
            name='date',
            field=models.DateTimeField(help_text='2000-2005', verbose_name='Дата'),
        ),
    ]
